name: Build and Deploy Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.14.0'

      - name: Set environment variables
        run: |
          echo "VITE_GOOGLE_MAPS_API_KEY=${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy
        run: rsync -avz --delete ./dist/ ubuntu@ec2-16-171-129-85.eu-north-1.compute.amazonaws.com:/home/ubuntu/Backend/flaskapp/build/
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}